### ISSUE TITLE
Terminal usage tutorial with simple_example.pddl crashing

### ISSUE THREAD

**Issue by devis12** [IntelligentRoboticsLabs/ros2_planning_system#121]
Good morning,
I've had an email discussion with @fmrico about the best and stablest setup for plansys2 and plansys2_examples packages since I've been studying ROS2 and your framework which I plan to use for building my master thesis project.
I'm using ROS2 Foxy on Ubuntu 20.04 LTS, @fmrico suggested me to go with the master branches in both repo and build them from scratch. In that scenario I cannot even run the terminal demo which you propose in this [page](https://intelligentroboticslab.gsyc.urjc.es/ros2_planning_system.github.io/tutorials/docs/terminal_usage.html) because when I give the command:
 `ros2 launch plansys2_bringup plansys2_bringup_launch_distributed.py model_file:=/tmp/simple_example.pddl`, 
 
 the process doesn't run smoothly (it automatically stops after a few seconds). I put the logs below.

**NOTE**: If I install the core packages via apt install and then run the launch demo for the terminal it works just fine. Moreover, if then I download all the examples from the foxy-devel branch of the [ros2_planning_system_examples](https://github.com/IntelligentRoboticsLabs/ros2_planning_system_examples) it seems that everything works (actually I tried out just the simplest one). However, considering multiple deprecation warnings and the fact that commits seem to happen more regularly and are more recent on the master branches, I don't want to work on something that maybe it's outdated, has bugs and/or lack some important features. So, before jumping into, I'd like to understand better what's not working here or, in case, if (you advise me in that direction) I can just leave it there for you as a hint of something that needs to be addressed and work with the specific versions for foxy (i.e. foxy-devel branch for the examples and the one installed via apt install for the core modules).
 
 `[INFO] [launch]: Default logging verbosity is set to INFO
/home/devis/ros2_ws/install/plansys2_bringup/share/plansys2_bringup/launch/plansys2_bringup_launch_distributed.py:102: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  lifecycle_manager_cmd = Node(
/home/devis/ros2_ws/install/plansys2_domain_expert/share/plansys2_domain_expert/launch/domain_expert_launch.py:42: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  domain_expert_cmd = Node(
/home/devis/ros2_ws/install/plansys2_domain_expert/share/plansys2_domain_expert/launch/domain_expert_launch.py:42: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  domain_expert_cmd = Node(
/home/devis/ros2_ws/install/plansys2_problem_expert/share/plansys2_problem_expert/launch/problem_expert_launch.py:42: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  domain_expert_cmd = Node(
/home/devis/ros2_ws/install/plansys2_problem_expert/share/plansys2_problem_expert/launch/problem_expert_launch.py:42: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  domain_expert_cmd = Node(
/home/devis/ros2_ws/install/plansys2_planner/share/plansys2_planner/launch/planner_launch.py:33: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  planner_cmd = Node(
/home/devis/ros2_ws/install/plansys2_planner/share/plansys2_planner/launch/planner_launch.py:33: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  planner_cmd = Node(
/home/devis/ros2_ws/install/plansys2_executor/share/plansys2_executor/launch/executor_launch.py:46: UserWarning: The parameter 'node_executable' is deprecated, use 'executable' instead
  executor_cmd = Node(
/home/devis/ros2_ws/install/plansys2_executor/share/plansys2_executor/launch/executor_launch.py:46: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  executor_cmd = Node(
[INFO] [domain_expert_node-1]: process started with pid [92445]
[INFO] [problem_expert_node-2]: process started with pid [92447]
[INFO] [planner_node-3]: process started with pid [92449]
[INFO] [executor_node-4]: process started with pid [92451]
[INFO] [lifecycle_manager_node-5]: process started with pid [92453]
[domain_expert_node-1] RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED is now ignored.  Please set RCUTILS_LOGGING_USE_STDOUT and RCUTILS_LOGGING_BUFFERED_STREAM to control the stream and the buffering of log messages.
[problem_expert_node-2] RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED is now ignored.  Please set RCUTILS_LOGGING_USE_STDOUT and RCUTILS_LOGGING_BUFFERED_STREAM to control the stream and the buffering of log messages.
[lifecycle_manager_node-5] RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED is now ignored.  Please set RCUTILS_LOGGING_USE_STDOUT and RCUTILS_LOGGING_BUFFERED_STREAM to control the stream and the buffering of log messages.
[planner_node-3] RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED is now ignored.  Please set RCUTILS_LOGGING_USE_STDOUT and RCUTILS_LOGGING_BUFFERED_STREAM to control the stream and the buffering of log messages.
[domain_expert_node-1] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
[domain_expert_node-1]   what():  No parameter value set
[executor_node-4] RCUTILS_CONSOLE_STDOUT_LINE_BUFFERED is now ignored.  Please set RCUTILS_LOGGING_USE_STDOUT and RCUTILS_LOGGING_BUFFERED_STREAM to control the stream and the buffering of log messages.
[problem_expert_node-2] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
[problem_expert_node-2]   what():  No parameter value set
[lifecycle_manager_node-5] [WARN] [1620985753.364889905] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[planner_node-3] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
[planner_node-3]   what():  No parameter value set
[lifecycle_manager_node-5] [WARN] [1620985753.367451567] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[lifecycle_manager_node-5] [WARN] [1620985753.369538229] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[lifecycle_manager_node-5] [INFO] [1620985753.371585513] [lifecycle_manager_node]: Creating client for service [domain_expert/get_state]
[lifecycle_manager_node-5] [INFO] [1620985753.371644973] [lifecycle_manager_node]: Creating client for service [domain_expert/change_state]
[lifecycle_manager_node-5] [INFO] [1620985753.372364786] [lifecycle_manager_node]: Creating client for service [executor/get_state]
[lifecycle_manager_node-5] [INFO] [1620985753.372385234] [lifecycle_manager_node]: Creating client for service [executor/change_state]
[executor_node-4] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidParameterValueException'
[executor_node-4]   what():  No parameter value set
[lifecycle_manager_node-5] [INFO] [1620985753.373519442] [lifecycle_manager_node]: Creating client for service [planner/get_state]
[lifecycle_manager_node-5] [INFO] [1620985753.373553421] [lifecycle_manager_node]: Creating client for service [planner/change_state]
[lifecycle_manager_node-5] [INFO] [1620985753.374250556] [lifecycle_manager_node]: Creating client for service [problem_expert/get_state]
[lifecycle_manager_node-5] [INFO] [1620985753.374283027] [lifecycle_manager_node]: Creating client for service [problem_expert/change_state]
[ERROR] [domain_expert_node-1]: process has died [pid 92445, exit code -6, cmd '/home/devis/ros2_ws/install/plansys2_domain_expert/lib/plansys2_domain_expert/domain_expert_node --ros-args -r __node:=domain_expert -r __node:=domain_expert -r __ns:=/ --params-file /tmp/launch_params_mftvfqiz --params-file /home/devis/ros2_ws/install/plansys2_bringup/share/plansys2_bringup/params/plansys2_params.yaml'].
[ERROR] [planner_node-3]: process has died [pid 92449, exit code -6, cmd '/home/devis/ros2_ws/install/plansys2_planner/lib/plansys2_planner/planner_node --ros-args -r __node:=planner -r __node:=planner -r __ns:=/ --params-file /home/devis/ros2_ws/install/plansys2_bringup/share/plansys2_bringup/params/plansys2_params.yaml'].
[ERROR] [problem_expert_node-2]: process has died [pid 92447, exit code -6, cmd '/home/devis/ros2_ws/install/plansys2_problem_expert/lib/plansys2_problem_expert/problem_expert_node --ros-args -r __node:=problem_expert -r __node:=problem_expert -r __ns:=/ --params-file /tmp/launch_params_wplcg2iq --params-file /home/devis/ros2_ws/install/plansys2_bringup/share/plansys2_bringup/params/plansys2_params.yaml'].
[ERROR] [executor_node-4]: process has died [pid 92451, exit code -6, cmd '/home/devis/ros2_ws/install/plansys2_executor/lib/plansys2_executor/executor_node --ros-args -r __node:=executor -r __node:=executor -r __ns:=/ --params-file /tmp/launch_params_j1vfczg1 --params-file /home/devis/ros2_ws/install/plansys2_bringup/share/plansys2_bringup/params/plansys2_params.yaml'].
[lifecycle_manager_node-5] [ERROR] [1620985756.375203213] [lifecycle_manager_node]: Service /domain_expert/change_state is not available.
[INFO] [lifecycle_manager_node-5]: process has finished cleanly [pid 92453]`

**Comment by fmrico** [comment]
Hi @devis12 

Fixed in #113 

Thanks!!!
