### ISSUE TITLE
Terminal crashing when setting a predicate with no args

### ISSUE THREAD

**Issue by devis12** [IntelligentRoboticsLabs/ros2_planning_system#124]
I put here the code for a basic hanoi domain in pddl, in which you can see there is a predicate with no args (not_moving).

`;; domain file: hanoi-domain.pddl

(define (domain hanoi-domain)

    (:requirements :strips :typing :adl :fluents :durative-actions)

    ;; Types ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

    (:types
        disk
    );; end Types ;;;;;;;;;;;;;;;;;;;;;;;;;

    (:predicates 
        (clear ?disk - disk)
        (on ?disk1 ?disk2 - disk)
        (smaller ?disk1 ?disk2 - disk)
        (not_moving)
    )

    (:durative-action moveOnTop
        :parameters (?disk ?from ?to - disk)
        :duration ( = ?duration 5)
        :condition (and
            (at start(clear ?disk))
            (at start(clear ?to))
            (at start(on ?disk ?from))
            (at start(smaller ?disk ?to))
            (at start(not_moving))
        )

        :effect (and
            (at start(clear ?from))
            (at start(not(on ?disk ?from)))
            (at start(not(not_moving)))

            (at end(not_moving))
            (at end(on ?disk ?to))
            (at end(not(clear ?to)))

        )
    )
)

If I write:
`get model predicate not_moving` 
I can see that it is correctly loaded, 

but when I go with:
`set predicate (not_moving)`
the process just stops as for the case of a not valid predicate (it'd be nice to have errors and not crashes also in that scenario).

**Comment by fmrico** [comment]
Hi @devis12 

As soon as I merge #126, it will be fixed.

Thanks for reporting!!
