### ISSUE TITLE
Plan no found in BT Tutorial.

### ISSUE THREAD

**Issue by tammerb** [IntelligentRoboticsLabs/ros2_planning_system#142]
In the Behavior Tree tutorial, after entering the instances, predicates, and goal for the car assembly example, when trying to `run` the Plansys2 terminal returns:
`[ERROR] [1624076520.251465508] [planner_client]: /planner/get_plan: Plan not found
Plan could not be computed`

When trying `get plan` the terminal returns:
`[ERROR] [1624076736.175475442] [planner_client]: /planner/get_plan: Plan not found
No se ha encontrado plan`

**Comment by fmrico** [comment]
Fixing in https://github.com/IntelligentRoboticsLabs/ros2_planning_system_examples/pull/22

Thanks for notifying.
