### ISSUE TITLE
Provide own problem.pddl into plansys2

### ISSUE THREAD

**Issue by Splinter1984** [IntelligentRoboticsLabs/ros2_planning_system#170]
I have a question. I see that plansys2 can generate Problem file from terminal commands. Is it possible for me to give plansys2 Problem file written by me?

**Comment by fmrico** [comment]
Hi @Splinter1984 

It should be in /tmp. May you check it out?

Best

**Comment by roveri-marco** [comment]
Hi, I'll be interested to know as well if it is possible!

**Comment by Splinter1984** [comment]
Hi @roveri-marco
As follows from the analysis of the code in the 'master' branch, this is currently not implemented.

**Comment by roveri-marco** [comment]
Indeed, however in the PR #200 I've added this feature. I'm finalizing few things and then I'll commit, so that if there are no other problems it can be merged in the master.
