### ISSUE TITLE
master do not compile on foxy

### ISSUE THREAD

**Issue by roveri-marco** [IntelligentRoboticsLabs/ros2_planning_system#185]
I've done a git pull on my previously downloaded version on the master, and the compilation failed. The reason being a missing include and the use of a method for the logger that is only supported in galactic or latest versions of ROS2 of rclcpp. In the patch, there are the changes I had to apply to have it compile successfully.

[compile.txt](https://github.com/IntelligentRoboticsLabs/ros2_planning_system/files/8072764/compile.txt)

Would it be possible to have a conditional compilation for the set_level method in the logger?

I belive that If galactic is needed, then it shall be properly stated.

I'm using foxy updated from the official repo in binary form, and running under Ubuntu 20.04.3 LTS, with g++ 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by sarcasticnature** [comment]
This issue is relevant: #179

**Comment by roveri-marco** [comment]
Although the <iomanip> seems to be not needed in galactic, from a programming point of view, the inclusion of needed header for used methods is a good practice instead of relying on other packages including them, especially if they are standard libraries.

As far as the set_level, I understand that now the master is for galactic, however, since it is a simple call to enable debugging it seems a minor change, and it might be conditioned to be in the galactic branch of ROS2 and disable in the other case, or using the proper code to enable that. 

These are just suggestions, and of course you are free to consider them or ignore thus closing this issue.

**Comment by fmrico** [comment]
Hi all,

As said in #179, `master` points to `Galactic`. But, I understand that removing only this call, which is not critical, could make it compile also in Foxy. I will be happy to accept a PR only removing this call. Please, @roveri-marco , instead of attaching patch files, contribute following the usual way, as I described some time ago in https://github.com/IntelligentRoboticsLabs/ros2_planning_system/issues/168#issuecomment-994393296 .

Best
Francisco

**Comment by roveri-marco** [comment]
Hi Francisco and all,

Sure I'll do as suggested in the forthcoming days.

Best
Marco

**Comment by fmrico** [comment]
Fixed in #187
