### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by roveri-marco** [IntelligentRoboticsLabs/ros2_planning_system#194]
This is not a bug, but a feature request. 

It would be worth having the possibility to upload a plan generated externally to the plansy2 infrastructure for then executing it.
From the plansys2 terminal, this will simplify interaction.  This for instance is very useful to validate certain scenarios without having to specify the instances/predicates/functions/goals, call the planner and then execute the plan. In this case, one can simply specify instances/predicates/functions and then can load a plan, and execute it without calling the planner.
But also from the overall architecture, I think that having the possibility to send a plan manually specified to the system is an interesting use case.

Another interesting feature for the terminal would be to load a set of commands from a file. With this feature, it is much easier to deal with the terminal. Indeed, one can write the commands in the file, and simply load the script without having to copy-paste the commands from the file to the terminal.

I will be willing to work directly on these features (especially the second)

**Comment by fmrico** [comment]
Hi @roveri-marco 

> It would be worth having the possibility to upload a plan generated externally to the plansy2 infrastructure for then executing it.
> From the plansys2 terminal, this will simplify interaction. This for instance is very useful to validate certain scenarios without having to specify the instances/predicates/functions/goals, call the planner and then execute the plan. In this case, one can simply specify instances/predicates/functions and then can load a plan, and execute it without calling the planner.
> But also from the overall architecture, I think that having the possibility to send a plan manually specified to the system is an interesting use case.

I think that most of this functionality is already there. I did something similar in #192. Maybe we could extend [ExecutePlan.action](https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/16b2dee52faa3bca1dfaf1ac8824bf0a8ac496a4/plansys2_msgs/action/ExecutePlan.action) with an optional entry in the request with the plan. If it is void, ask a plan to the planner.

> Another interesting feature for the terminal would be to load a set of commands from a file. With this feature, it is much easier to deal with the terminal. Indeed, one can write the commands in the file, and simply load the script without having to copy-paste the commands from the file to the terminal.

Well, you can do it by using the input redirection operator '<' in the shell

Best
Francisco

**Comment by roveri-marco** [comment]
@fmrico I'll check #192 and I'll see...

For the second part It is not enough since if you would like then to continue interacting with the terminal it is not easy.
I've already finished implementing this last feature and I'm testing it. I've also added an help command that I believe it is useful for interacting with the terminal. I'll add a PR soon.

Best
Marco

**Comment by roveri-marco** [comment]
PR #200 added all the features listed here, thus we can close this issue.
