### ISSUE TITLE
Plan execution fails with multiples actions ...

### ISSUE THREAD

**Issue by teyssieuman** [IntelligentRoboticsLabs/ros2_planning_system#67]
This issue is linked to the following pull request on the `ros2_planning_system_example` repository :

https://github.com/IntelligentRoboticsLabs/ros2_planning_system_examples/pull/12

The execution of the plan fails:
- it executes simultaneously the two first actions that shall be executed one after the other.
- it fails and stop immediately after the execution of those actions.

**Comment by teyssieuman** [comment]
@fmrico : Except if you thing it more may be done, i think that this case can be close !

**Comment by fmrico** [comment]
Lets close!!
