### ISSUE TITLE
Unreshable code.

### ISSUE THREAD

**Issue by teyssieuman** [IntelligentRoboticsLabs/ros2_planning_system#77]
https://github.com/IntelligentRoboticsLabs/ros2_planning_system/blob/e65a5559c5d82efae8cc28e6030bb4267b870869/plansys2_executor/src/plansys2_executor/ExecutorNode.cpp#L168

**Comment by fmrico** [comment]
You are right. Do you want to open a PR to remove it?

Thanks!!

**Comment by fmrico** [comment]
Fixed in #78 . Closing 

Thanks!!
