### ISSUE TITLE
ZMQ default port

### ISSUE THREAD

**Issue by fmrico** [IntelligentRoboticsLabs/ros2_planning_system#98]
Hi @xydesa 

In the experiments of this week, we found some problems with the default ports used by ZMQ. They are the same used by Nav2, and it produces an exception. It makes me think that we should change them because it is probably a widely used configuration.

Do you think that the best fix is only to change our default ports?

Best

**Comment by xydesa** [comment]
Yes, I think just changing the default ports used by plansys2 should be enough.
